version: '3.1'
services:
    redis:
        container_name: 'redis'
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    postgres:
        container_name: 'postgres'
        image: 'postgres'
        working_dir: '/var/www'
        volumes:
            - './storage/_db:/var/lib/postgresql/data'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=laravel
        ports:
            - '12004:5432'
    adminer:
        container_name: 'adminer'
        image: 'adminer:latest'
        restart: 'always'
        ports:
            - '8080:8080'
        depends_on:
            -  'postgres'
    webserver:
        container_name: 'nginx'
        image: 'nginx:alpine'
        working_dir: '/var/www'
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '12000:80'
    php-fpm:
        container_name: 'php-fpm'
        build: 'phpdocker/php-fpm'
        working_dir: '/var/www'
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    composer:
        container_name: 'composer'
        build: 'phpdocker/php-fpm'
        working_dir: '/var/www'
        volumes:
            - '.:/var/www'

